=== ChinaSnake007/XML/Test3/1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xsd:element name="Library">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="Book" type="bookType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>

<xsd:complexType name="bookType">
    <xsd:sequence>
        <xsd:element name="BookName" type="xsd:string"/>
        <xsd:element name="Author" maxOccurs="unbounded">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="AuthorName" type="xsd:string"/>
                    <xsd:element name="Gender" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
        <xsd:element name="Publisher">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="PublisherName" type="xsd:string"/>
                    <xsd:element name="PublisherAddress">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="Provice" type="xsd:string"/>
                                <xsd:element name="City" type="xsd:string"/>
                                <xsd:element name="AddressDetail" type="xsd:string"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
        <xsd:element name="Price" type="xsd:decimal"/>
        <xsd:element name="BookNumber" type="xsd:integer"/>
        <xsd:element name="PublishDate" type="xsd:date"/>
        <xsd:element name="CatalogueDateTime" type="xsd:date"/>
        <xsd:element name="InStoreTime" type="xsd:date"/>
    </xsd:sequence>
    <xsd:attribute name="ISBN" type="xsd:string"/>
</xsd:complexType>


</xsd:schema>

=== ChinaSnake007/XML/Test3/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<Library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./1.xsd">
    <Book ISBN="978-5685-8648-4">
        <BookName>软件开发与项目管理</BookName>
        <Author>
            <AuthorName>杨森</AuthorName>
            <Gender>男</Gender>
        </Author>
        <Author>
            <AuthorName>郭永怀</AuthorName>
            <Gender>男</Gender>
        </Author>
        <Publisher>
            <PublisherName>高等教育出版社</PublisherName>
            <PublisherAddress>
                <Provice>北京市</Provice>
                <City>西城区</City>
                <AddressDetail>北京市西城区德外大街4号</AddressDetail>
            </PublisherAddress>
        </Publisher>
        <Price>33.8</Price>
        <BookNumber>20</BookNumber>
        <PublishDate>2015-04-01</PublishDate>
        <CatalogueDateTime>2015-04-01</CatalogueDateTime>
        <InStoreTime>2015-04-01</InStoreTime>
    </Book>
    <Book ISBN="978-5685-8648-4">
        <BookName>软件开发与项目管理</BookName>
        <Author>
            <AuthorName>杨森</AuthorName>
            <Gender>男</Gender>
        </Author>
        <Author>
            <AuthorName>郭永怀</AuthorName>
            <Gender>男</Gender>
        </Author>
        <Publisher>
            <PublisherName>高等教育出版社</PublisherName>
            <PublisherAddress>
                <Provice>北京市</Provice>
                <City>西城区</City>
                <AddressDetail>北京市西城区德外大街4号</AddressDetail>
            </PublisherAddress>
        </Publisher>
        <Price>33.8</Price>
        <BookNumber>20</BookNumber>
        <PublishDate>2015-04-01</PublishDate>
        <CatalogueDateTime>2015-04-01</CatalogueDateTime>
        <InStoreTime>2015-04-01</InStoreTime>
    </Book>
</Library>
