<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE orders [
<!ELEMENT orders (order+)>
<!ELEMENT order (orderInformation,ConsigneeInformation,PayAndDelivery,BillInformation,ProductList,PaymentInformation)>
<!ATTLIST orderInformation OrderID ID #REQUIRED>
<!ATTLIST orderInformation Orderstate (正在出库|正在配送|完成) "正在出库">
<!ELEMENT orderInformation (#PCDATA)>

<!ELEMENT ConsigneeInformation (Consignee,Address,FixedPhone,MobilePhone,Email)>
<!ELEMENT Consignee (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT FixedPhone (#PCDATA)>
<!ELEMENT MobilePhone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

<!ATTLIST PayAndDelivery PayMethod (在线支付|邮局付款|公司转账|分期付款|货到付款) "货到付款">
<!ATTLIST PayAndDelivery DeliveryMethod (工作日送货|双休日与假日送货|工作日-双休日与假日均可送货) "工作日-双休日与假日均可送货">
<!ELEMENT PayAndDelivery (#PCDATA)>

<!ELEMENT BillInformation (BillTitle, BillContent)>
<!ATTLIST BillInformation BillType (普通发票|增值税发票) "普通发票">
<!ELEMENT BillTitle (#PCDATA)>
<!ELEMENT BillContent (#PCDATA)>

<!ELEMENT ProductList (Product+)>
<!ELEMENT Product (ProductID,ProductName,ProductPrice,ProductNumber)>
<!ELEMENT ProductID (#PCDATA)>
<!ELEMENT ProductName (#PCDATA)>
<!ELEMENT ProductPrice (#PCDATA)>
<!ELEMENT ProductNumber (#PCDATA)>

<!ELEMENT PaymentInformation (ProductAmount, Freight,Cashback,OrderAmount)>
<!ELEMENT ProductAmount (#PCDATA)>
<!ELEMENT Freight (#PCDATA)>
<!ELEMENT Cashback (#PCDATA)>
<!ELEMENT OrderAmount (#PCDATA)>
]>
<orders>
    <order>
        <orderInformation OrderID="sdffe"/>

        <ConsigneeInformation>
            <Consignee>张三</Consignee>
            <Address>连云港市山河镇</Address>
            <FixedPhone>86466371</FixedPhone>
            <MobilePhone>18151662007</MobilePhone>
            <Email>1805828047@qq.com</Email>
        </ConsigneeInformation>
        <PayAndDelivery/>
        <BillInformation>
            <BillTitle>1</BillTitle>
            <BillContent>支付信息</BillContent>
        </BillInformation>
        <ProductList>
            <Product>
                <ProductID>1</ProductID>
                <ProductName>牙刷</ProductName>
                <ProductPrice>25</ProductPrice>
                <ProductNumber>2</ProductNumber>
            </Product>
            <Product>
                <ProductID>2</ProductID>
                <ProductName>牙膏</ProductName>
                <ProductPrice>15</ProductPrice>
                <ProductNumber>3</ProductNumber>
            </Product>
        </ProductList>
        <PaymentInformation>
            <ProductAmount>25</ProductAmount>
            <Freight>25</Freight>
            <Cashback>5</Cashback>
            <OrderAmount>50</OrderAmount>
        </PaymentInformation>
    </order>
</orders>